---
# tasks file for epel_repository
- name: Check if epel-release is installed
  repoquery:
    name: epel-release
    query_type: installed
  register: repoquery_epel

- name: debug
  debug:
    msg: "{{ repoquery_epel }}"

- name: Install EPEL Repo RPM
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: not repoquery_epel.results.package_found

- name: insert the skip_if_unavailable option
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    section: epel
    option: skip_if_unavailable
    no_extra_spaces: True
    value: "{{ epelr_skip_if_unavailable | ternary('1','0') }}"

- name: Mark undesirable EPEL packages as excluded
  lineinfile:
    name: "{{item.filename}}"
    insertafter: "^\\[{{item.reponame}}\\]$"
    regexp: "^exclude=.*?fake_package_name-EXCLUDES-FOR-{{item.reponame}}-MANAGED-BY-ANSIBLE$"
    line: "exclude={{epelr_exclude}} fake_package_name-EXCLUDES-FOR-{{item.reponame}}-MANAGED-BY-ANSIBLE"
  with_items:
    - filename: /etc/yum.repos.d/epel.repo
      reponame: epel
    - filename: /etc/yum.repos.d/epel.repo
      reponame: epel-debuginfo
    - filename: /etc/yum.repos.d/epel.repo
      reponame: epel-source
    - filename: /etc/yum.repos.d/epel-testing.repo
      reponame: epel-testing
    - filename: /etc/yum.repos.d/epel-testing.repo
      reponame: epel-testing-debuginfo
    - filename: /etc/yum.repos.d/epel-testing.repo
      reponame: epel-testing-source
