---

- name: Get the routing subdomain from the master
  yedit:
    state: list
    src: /etc/origin/master/master-config.yaml
    key: routingConfig.subdomain
  register: subdomain
  run_once: true

# task to insall rpm
- name: install the latest version of openshift-scripts-devpreview
  yum:
    name: openshift-scripts-devpreview
    state: present

- name: Delete existing config map if necessary
  oc_configmap:
    state: absent
    name: customrouter
    namespace: default
  run_once: true

- name: Create customrouter configmap
  oc_configmap:
    state: present
    name: customrouter
    namespace: default
    from_file:
      template: /etc/openshift-online/templates/haproxy-config.template
  register: configmap_out
  run_once: true

- name: Add a volume to the router
  oc_volume:
    namespace: default
    kind: dc
    name: router
    vol_name: config-volume
    mount_type: configmap
    mount_path: /var/lib/haproxy/conf/custom
    configmap_name: customrouter
  run_once: true

- name: Add our env vars to new customrouter
  oc_env:
    kind: dc
    name: router
    env_vars:
      ROUTER_OVERRIDE_HOSTNAME: "false"
      ROUTER_CLOUD_DOMAIN: "{{ subdomain.result }}"
      TEMPLATE_FILE: /var/lib/haproxy/conf/custom/haproxy-config.template
      EXTENDED_VALIDATION: "true"
  run_once: true
