---
- name: create the /root/.docker directory
  file:
    state: directory
    path: /host/root/.docker
    mode: "0740"
    owner: root
    group: root

- name: copy docker config.json to shared config emptydir
  copy:
    remote_src: true
    src: /opt/secrets/docker-config.json
    dest: /host/root/.docker/config.json
    owner: root
    group: root

# Note: The next 3 tasks are trying to work around https://bugzilla.redhat.com/show_bug.cgi?id=1592503
#  When this bug is closed, these should be removed
- name: dig (lookup) the docker registry ip
  command: "dig +short docker-registry.default.svc.cluster.local"
  changed_when: false
  register: registry_ip_cmd

- name: debug docker registry ip
  debug:
    msg: "{{ registry_ip_cmd }}"

- name: create symlink for docker registry ip
  file:
    path: "/etc/docker/certs.d/{{ registry_ip_cmd.stdout }}:5000"
    src: "docker-registry.default.svc:5000"
    state: link
    force: True
  when: registry_ip_cmd.stdout != ''
#### END of https://bugzilla.redhat.com/show_bug.cgi?id=1592503
