---
g_default_zagg_server_config:
  targets:
  - name: local zaio
    type: zabbix
    trapper_server: oso-rhel7-zaio
    trapper_port: 10051
    api_url: http://oso-rhel7-zaio/zabbix/api_jsonrpc.php
    api_user: Admin
    api_password: zabbix
    ssl_verify: False
    path: /var/run/zagg/data/local_zaio
  templates:
  - Template Heartbeat
  - Template Zagg Server
  hostgroups:
  - Linux servers

g_default_zagg_server_user: zagg-user
g_default_zagg_server_password: zagg-password
