---
- hosts: localhost
  gather_facts: no
  vars:
    # This is the default value for g_zagg_client_config, override using zagg_client_vars.yml vars file
    g_zagg_client_config:
      host:
        name: "{{ g_hostname }}"
      zagg:
        host: zagg-server
        user: admin
        pass: zagg-password
      pcp:
        metrics:
        - kernel.all
        - swap.free
        - swap.length
        - swap.used
      heartbeat:
        templates:
        - Template Heartbeat # So we can send hearbeats
        - Template OS Linux  # So we can send host related metrics
        hostgroups:
        - Linux servers

    # This is the default value for g_zagg_client_cron, override using zagg_client_vars.yml vars file
    g_zagg_client_cron:
    - name: run pcp checks every 5 minutes
      minute: "*/5"
      job: /usr/bin/ops-zagg-client --send-pcp
    - name: run register every 15 minutes
      minute: "*/15"
      job: /usr/bin/ops-zagg-client --send-heartbeat

  pre_tasks:
  - stat:
      path: /secrets/zagg_client_vars.yml
    register: g_zagg_client_vars

  - include_vars: /secrets/zagg_client_vars.yml
    when: g_zagg_client_vars.stat.exists

  - fail: "msg=This playbook requires {{ item }} to be set and not empty."
    when: "{{ item }} is not defined or not {{ item }}"
    with_items:
    - g_zagg_client_config

  - name: Get hostname information from pminfo
    command: '/usr/bin/pminfo -f kernel.uname.nodename'
    changed_when: false
    register: g_pminfo_hostname_output

  - set_fact:
      g_hostname: "CTR-{{ g_pminfo_hostname_output.stdout_lines[2][11:-1] }}"

  - debug: var=g_hostname

  - debug: var=g_zagg_client_config

  - name: Generate the zagg_client.yaml config file
    copy:
      content: "{{ g_zagg_client_config | to_nice_yaml }}"
      dest: /etc/openshift_tools/zagg_client.yaml
      mode: "644"

  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items: g_zagg_client_cron
