---
- name: Include lib_openshift
  include_role:
    name: tools_roles/lib_openshift

# Quota support
# Can disable quota support by passing in "osmsc_enable_quota: False"
#
- name: label designated projects to exclude from pv quotas
  oc_label:
    state: add
    kind: namespace
    name: "{{ item }}"
    labels:
    - key: "{{ osmsc_exclude_quota_label }}"
      value: "False"
  with_items: "{{ osmsc_projects_to_exclude }}"
  run_once: True
  when: osmsc_enable_quotas

- name: Ensure Quotas are set for storage
  oc_obj:
    kind: ClusterResourceQuota
    name: persistent-volume
    content:
      path: /tmp/osmsc_persistent_volume_quota
      data:
        kind: ClusterResourceQuota
        apiVersion: v1
        metadata:
          name: persistent-volume
        spec:
          selector:
            annotations: null
            labels:
              matchExpressions:
              - key: "{{ osmsc_exclude_quota_label }}"
                operator: DoesNotExist
          quota:
            hard:
              requests.storage: "{{ osmsc_cluster_pv_quota }}"
  run_once: true
  when: osmsc_enable_quotas
  notify:
  - restart openshift master services
