---
- name: Grab the current firewall rules
  command: /usr/sbin/iptables -nL
  register: iptables_list_out
  changed_when: False

- name: Add the iptables rule if not found
  command: /usr/sbin/iptables -A INPUT -p tcp --dport 8080 -j ACCEPT -m comment --comment "haproxy"
  when: not 'tcp dpt:8080 /* haproxy */' in iptables_list_out.stdout
  register: iptables_add_out

- name: Save the iptables rules if one was added
  command: /usr/libexec/iptables/iptables.init save
  when: iptables_add_out.changed

- name: install the haproxy package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - haproxy

- name: Install haproxy.cfg file
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart haproxy

- name: create the haproxy systemd add on dir
  file:
   path: /etc/systemd/system/haproxy.service.d
   state: directory
   owner: root
   group: root
   mode: 0755

- name: Make systemd restart haproxy if it goes down
  copy:
    src: haproxy_systemd_restart.conf
    dest: /etc/systemd/system/haproxy.service.d/restart.conf
    owner: root
    group: root
    mode: 0644

- name: start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: True
